import { VALIDATOR_PROMPT } from './prompts/system';
import { getGeminiModel } from './gemini';

export interface ValidationResult {
  valid: boolean;
  code: string;
  error?: string;
}

/**
 * Sanitize common Mermaid syntax issues generated by LLMs
 */
function sanitizeMermaidCode(code: string): string {
  let result = code;

  // Remove markdown fences
  result = result
    .replace(/^```mermaid\n?/i, '')
    .replace(/^```\n?/, '')
    .replace(/\n?```$/, '')
    .trim();

  // Fix double curly braces {{ }} → convert to regular nodes [ ]
  // LLMs often generate {{text}} which is hexagon syntax and causes errors in flowcharts
  result = result.replace(/\{\{"([^"]*?)"\}\}/g, '["$1"]');
  result = result.replace(/\{\{([^}]*?)\}\}/g, '[$1]');

  // Fix unescaped quotes inside node labels
  // e.g., ["text with "quotes""] → ["text with quotes"]
  result = result.replace(/\["([^"]*)"([^"]*)"([^"]*)"\]/g, '["$1$2$3"]');

  // Fix common LLM mistake: using > < in labels without quotes
  // Wrap unquoted labels containing special chars
  result = result.replace(
    /-->\|([^"|]*[<>][^"|]*)\|/g,
    (_, label) => `-->|"${label}"|`
  );

  // Remove any trailing semicolons after node definitions (not valid in all contexts)
  result = result.replace(/;\s*$/gm, '');

  // Fix empty subgraph titles
  result = result.replace(/subgraph\s*\n/g, 'subgraph Untitled\n');

  return result;
}

export async function validateMermaidCode(code: string): Promise<ValidationResult> {
  const cleaned = sanitizeMermaidCode(code);

  if (!cleaned) {
    return { valid: false, code: cleaned, error: 'Empty code' };
  }

  const validStarters = [
    'graph', 'flowchart', 'sequenceDiagram', 'classDiagram',
    'erDiagram', 'stateDiagram', 'gantt', 'pie', 'gitgraph',
    'mindmap', 'timeline', 'sankey', 'block',
  ];

  const hasValidStart = validStarters.some(s =>
    cleaned.toLowerCase().startsWith(s.toLowerCase())
  );

  if (!hasValidStart) {
    return { valid: false, code: cleaned, error: 'Missing diagram type declaration' };
  }

  return { valid: true, code: cleaned };
}

export async function fixMermaidCode(code: string, error: string): Promise<string> {
  const prompt = VALIDATOR_PROMPT
    .replace('{code}', code)
    .replace('{error}', error);

  const model = getGeminiModel();
  const result = await model.generateContent(prompt);
  const text = result.response.text();

  return sanitizeMermaidCode(text);
}
